name: Fetch Instagram Posts

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  fetch-instagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Instagram posts
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        run: |
          # Create the directory if it doesn't exist
          mkdir -p assets/data

          # Fetch Instagram posts and save them as a JSON file
          curl -s -o assets/data/instagram-posts.json \
            "https://graph.instagram.com/me/media?fields=id,caption,media_type,media_url,permalink,timestamp&access_token=$INSTAGRAM_ACCESS_TOKEN"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/data/instagram-posts.json
          git commit -m "Update Instagram posts" || echo "No changes to commit"
          git push
